/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.entidade.Usuario;

/**
 *
 * @author lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VW_TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    public TelaPrincipal(Usuario us) {
        initComponents();
        jTnome.setText(us.getusnome());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBcadastrarmorador = new javax.swing.JButton();
        jBcadastrarapartamento = new javax.swing.JButton();
        jBcadastrarbloco = new javax.swing.JButton();
        jBcadastrarusuario = new javax.swing.JButton();
        JDPAreaTrabalho = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCadAp = new javax.swing.JMenuItem();
        jMmo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Morador Home");
        setResizable(false);

        jToolBar1.setRollover(true);

        jBcadastrarmorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/heart 55x.png"))); // NOI18N
        jBcadastrarmorador.setToolTipText("Cadastrar Morador");
        jBcadastrarmorador.setFocusable(false);
        jBcadastrarmorador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBcadastrarmorador.setPreferredSize(new java.awt.Dimension(55, 55));
        jBcadastrarmorador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBcadastrarmorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarmoradorActionPerformed(evt);
            }
        });
        jToolBar1.add(jBcadastrarmorador);

        jBcadastrarapartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/urban 55x.png"))); // NOI18N
        jBcadastrarapartamento.setToolTipText("Cadastro de Apartamento");
        jBcadastrarapartamento.setFocusable(false);
        jBcadastrarapartamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBcadastrarapartamento.setPreferredSize(new java.awt.Dimension(55, 55));
        jBcadastrarapartamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBcadastrarapartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarapartamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBcadastrarapartamento);

        jBcadastrarbloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/building 55x.png"))); // NOI18N
        jBcadastrarbloco.setToolTipText("Cadastro de Bloco");
        jBcadastrarbloco.setFocusable(false);
        jBcadastrarbloco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBcadastrarbloco.setPreferredSize(new java.awt.Dimension(55, 55));
        jBcadastrarbloco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBcadastrarbloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarblocoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBcadastrarbloco);

        jBcadastrarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/work 55x.png"))); // NOI18N
        jBcadastrarusuario.setToolTipText("Cadastro de Usuario");
        jBcadastrarusuario.setFocusable(false);
        jBcadastrarusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBcadastrarusuario.setPreferredSize(new java.awt.Dimension(55, 55));
        jBcadastrarusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBcadastrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarusuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(jBcadastrarusuario);

        JDPAreaTrabalho.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");

        jTnome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTnome.setForeground(new java.awt.Color(255, 255, 255));
        jTnome.setText("***");

        JDPAreaTrabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDPAreaTrabalho.setLayer(jTnome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDPAreaTrabalhoLayout = new javax.swing.GroupLayout(JDPAreaTrabalho);
        JDPAreaTrabalho.setLayout(JDPAreaTrabalhoLayout);
        JDPAreaTrabalhoLayout.setHorizontalGroup(
            JDPAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDPAreaTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JDPAreaTrabalhoLayout.setVerticalGroup(
            JDPAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDPAreaTrabalhoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(JDPAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(612, Short.MAX_VALUE))
        );

        jLabel1.setText("Todos os direitos reservados: Lucas Pimentel Vieira");

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N

        jCadAp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCadAp.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jCadAp.setText("Apartamento");
        jCadAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadApActionPerformed(evt);
            }
        });
        jMenu1.add(jCadAp);

        jMmo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMmo.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMmo.setText("Moradores");
        jMmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmoActionPerformed(evt);
            }
        });
        jMenu1.add(jMmo);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMenuItem2.setText("Bloco");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu4.setMnemonic('R');
        jMenu4.setText("Consulta");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMenuItem6.setText("Apartamento");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jMenuItem7.setText("Moradores");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPAreaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(jLabel1)))
                .addContainerGap(650, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDPAreaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarmoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarmoradorActionPerformed

        TelaCadMorador cd = new TelaCadMorador();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jBcadastrarmoradorActionPerformed

    private void jBcadastrarapartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarapartamentoActionPerformed
        // TODO add your handling code here:
        TelaCadApartamento cd = new TelaCadApartamento();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jBcadastrarapartamentoActionPerformed

    private void jBcadastrarblocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarblocoActionPerformed
        // TODO add your handling code here:
        TelaCadBloco cd = new TelaCadBloco();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jBcadastrarblocoActionPerformed

    private void jBcadastrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarusuarioActionPerformed
        // TODO add your handling code here:
        TelaCadUsuario cd = new TelaCadUsuario();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jBcadastrarusuarioActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        TelaListaMoradores cd = new TelaListaMoradores();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TelaListaApartamento cd = new TelaListaApartamento();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jCadApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadApActionPerformed
        // TODO add your handling code here:
        TelaCadApartamento cd = new TelaCadApartamento();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);

    }//GEN-LAST:event_jCadApActionPerformed

    private void jMmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmoActionPerformed
        // TODO add your handling code here:
        TelaCadMorador cd = new TelaCadMorador();
        JDPAreaTrabalho.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_jMmoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPAreaTrabalho;
    private javax.swing.JButton jBcadastrarapartamento;
    private javax.swing.JButton jBcadastrarbloco;
    private javax.swing.JButton jBcadastrarmorador;
    private javax.swing.JButton jBcadastrarusuario;
    private javax.swing.JMenuItem jCadAp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMmo;
    private javax.swing.JLabel jTnome;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
